apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: simple-cnn
  namespace: default
spec:
  predictor:
    model:
      modelFormat:
        name: tensorflow
      storageUri: "pvc://simple-cnn-pvc/"
  transformer:
    containers:
    - name: kserve-container
      image: tomasconti02/transformer_final:v1
      command: ["python", "-m", "transformer"]
      args:
      - --model_names
      - "simple-cnn,simple-cnn-test"
      - --namespace
      - "default"

---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: simple-cnn-test
  namespace: default
spec:
  predictor:
    model:
      modelFormat:
        name: tensorflow
      storageUri: "pvc://simple-cnn-test-pvc/"
  transformer:
    containers:
    - name: kserve-container
      image: tomasconti02/transformer_final:v1
      command: ["python", "-m", "transformer"]
      args:
      - --model_names
      - "simple-cnn,simple-cnn-test"
      - --namespace
      - "default"
